-- 焼き鳥セット対応: 串ごとに「味(たれ/塩)」「種類(もも/ねぎま/かわ等)」を選べるようにする。
-- 味・種類は/admin画面から追加・編集できるようマスタテーブル化する(spec変更: 2026-08-03)。
-- 価格は種類・味に関係なくセット単価固定のため、価格差分の仕組みは持たない。

create table if not exists yakitori_flavors (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists yakitori_types (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table menu_items
  add column if not exists is_yakitori_set boolean not null default false,
  add column if not exists yakitori_skewer_count integer;

alter table menu_items
  drop constraint if exists menu_items_yakitori_skewer_count_check;
alter table menu_items
  add constraint menu_items_yakitori_skewer_count_check
    check (
      (is_yakitori_set = false and yakitori_skewer_count is null)
      or (is_yakitori_set = true and yakitori_skewer_count > 0)
    );

-- 串ごとの選択(味・種類の名前スナップショット)を保持する。メニュー改定後も過去注文の
-- 表示が壊れないよう、他のスナップショット列と同様に「名前」をそのまま焼き付ける。
alter table order_items
  add column if not exists yakitori_selections jsonb;

alter table yakitori_flavors enable row level security;
alter table yakitori_types enable row level security;

drop policy if exists "yakitori_flavors_select" on yakitori_flavors;
create policy "yakitori_flavors_select" on yakitori_flavors for select to anon, authenticated using (true);
drop policy if exists "yakitori_flavors_insert" on yakitori_flavors;
create policy "yakitori_flavors_insert" on yakitori_flavors for insert to anon, authenticated with check (true);
drop policy if exists "yakitori_flavors_update" on yakitori_flavors;
create policy "yakitori_flavors_update" on yakitori_flavors for update to anon, authenticated using (true) with check (true);

drop policy if exists "yakitori_types_select" on yakitori_types;
create policy "yakitori_types_select" on yakitori_types for select to anon, authenticated using (true);
drop policy if exists "yakitori_types_insert" on yakitori_types;
create policy "yakitori_types_insert" on yakitori_types for insert to anon, authenticated with check (true);
drop policy if exists "yakitori_types_update" on yakitori_types;
create policy "yakitori_types_update" on yakitori_types for update to anon, authenticated using (true) with check (true);

insert into yakitori_flavors (name, sort_order) values
  ('たれ', 1),
  ('塩', 2)
on conflict (name) do nothing;

insert into yakitori_types (name, sort_order) values
  ('もも', 1),
  ('ねぎま', 2),
  ('かわ', 3)
on conflict (name) do nothing;
