-- 文化祭モバイルオーダー: 初期スキーマ (docs/spec.md 準拠)
--
-- 採番方針: orders.id / orders.number は端末(localStorage)側で発番し、クライアントから
-- 確定値を渡す。DB側に auto-increment / sequence / default の採番機構を一切持たせない
-- (docs/spec.md の絶対原則: 「Supabaseに採番させない」)。

create table if not exists categories (
  id bigint generated by default as identity primary key,
  name text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists menu_items (
  id bigint generated by default as identity primary key,
  category_id bigint references categories(id) on delete set null,
  name text not null,
  price integer not null check (price >= 0),
  emoji text,
  -- is_available: 売り切れ(当日中に何度でも反転しうる)。is_active: 商品自体の非表示(論理削除)。
  is_available boolean not null default true,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- orders.id はクライアント(端末)が crypto.randomUUID() 等で生成し、QRに埋め込んだ値をそのまま渡す。
-- 冪等キーとして機能させるため、DB側にデフォルト値を設定しない = 渡し忘れは意図的にエラーにする。
create table if not exists orders (
  id uuid primary key,
  prefix text not null check (prefix in ('A', 'B')),
  seq integer not null check (seq > 0),
  number text not null,
  status text not null default 'received'
    check (status in ('received', 'cooking', 'ready', 'handed', 'cancelled')),
  total integer not null check (total >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  -- 端末ローカル採番が壊れて重複発番した場合に検知できるよう、DB側でも一意性を保証する
  -- (これは採番そのものをDBにやらせているわけではない: あくまで事後チェック)。
  unique (prefix, seq)
);

create table if not exists order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references orders(id) on delete cascade,
  menu_item_id bigint references menu_items(id) on delete set null,
  -- メニュー改定後も過去注文の表示が壊れないよう、注文時点の内容を焼き付ける。
  name_snapshot text not null,
  price_snapshot integer not null check (price_snapshot >= 0),
  qty integer not null check (qty > 0)
);

create table if not exists push_subscriptions (
  id bigint generated by default as identity primary key,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  created_at timestamptz not null default now()
);

create index if not exists order_items_order_id_idx on order_items (order_id);
create index if not exists orders_status_idx on orders (status);
create index if not exists menu_items_category_id_idx on menu_items (category_id);

-- updated_at 自動更新
create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists set_updated_at on orders;
create trigger set_updated_at
  before update on orders
  for each row execute function set_updated_at();

drop trigger if exists set_updated_at on menu_items;
create trigger set_updated_at
  before update on menu_items
  for each row execute function set_updated_at();

-- RLS: 認証なしの前提のため、anon ロールに必要な操作を明示的に許可する。
-- 削除は行わない(論理削除のみ)ため delete ポリシーは用意しない。
alter table categories enable row level security;
alter table menu_items enable row level security;
alter table orders enable row level security;
alter table order_items enable row level security;
alter table push_subscriptions enable row level security;

drop policy if exists "categories_select" on categories;
create policy "categories_select" on categories for select to anon, authenticated using (true);

drop policy if exists "menu_items_select" on menu_items;
create policy "menu_items_select" on menu_items for select to anon, authenticated using (true);
drop policy if exists "menu_items_insert" on menu_items;
create policy "menu_items_insert" on menu_items for insert to anon, authenticated with check (true);
drop policy if exists "menu_items_update" on menu_items;
create policy "menu_items_update" on menu_items for update to anon, authenticated using (true) with check (true);

drop policy if exists "orders_select" on orders;
create policy "orders_select" on orders for select to anon, authenticated using (true);
drop policy if exists "orders_insert" on orders;
create policy "orders_insert" on orders for insert to anon, authenticated with check (true);
drop policy if exists "orders_update" on orders;
create policy "orders_update" on orders for update to anon, authenticated using (true) with check (true);

drop policy if exists "order_items_select" on order_items;
create policy "order_items_select" on order_items for select to anon, authenticated using (true);
drop policy if exists "order_items_insert" on order_items;
create policy "order_items_insert" on order_items for insert to anon, authenticated with check (true);

drop policy if exists "push_subscriptions_insert" on push_subscriptions;
create policy "push_subscriptions_insert" on push_subscriptions for insert to anon, authenticated with check (true);

-- 初期メニュー(既存 lib/menu.ts のハードコード値を移植)
insert into categories (id, name, sort_order) values (1, '通常メニュー', 0)
  on conflict (id) do nothing;

insert into menu_items (id, category_id, name, price, emoji, sort_order) values
  (1, 1, '焼き鳥', 200, '🐔', 1),
  (2, 1, 'かき氷', 250, '🍧', 2),
  (3, 1, 'コーラ', 150, '🥤', 3),
  (4, 1, '水', 100, '💧', 4)
  on conflict (id) do nothing;

-- 明示IDでのシード後、identityシーケンスが未進行のままだと以降のinsertでid衝突するため進めておく。
select setval(pg_get_serial_sequence('categories', 'id'), (select max(id) from categories));
select setval(pg_get_serial_sequence('menu_items', 'id'), (select max(id) from menu_items));
